module.exports = [
    "Aegis Defense",
    "Alliance Incarceration Concern",
    "Bill Turner",
    "Broo Tarquin",
    "Canonn Gnosis Division",
    "Captain Banner",
    "Chloe Sedesi",
    "Colonel Bris Dekker",
    "Didi Vatermann",
    "Elui Shera",
    "Elvira Martuuk",
    "Etienne Dorn",
    "Federal Internment Corporation",
    "Felicity Farseer",
    "Hera Tani",
    "Imperial Detainment Company",
    "Independent Detention Foundation",
    "Juri Ishmaak",
    "Kit Lange",
    "Lei Cheung",
    "Lex Avermann",
    "Liz Ryder",
    "Lori Jameson",
    "Marco Qwent",
    "Marsha Hicks",
    "Matt 'The Gunner' Sorbis",
    "Mel Brandon",
    "Petra Olmanova",
    "Pilots' Federation Local Branch",
    "Pilots Federation Local Branch",   // incase some idiot sends old data
    "Professor Palin",
    "Ram Tah",
    "Selene Jean",
    "The Dweller",
    "The Sarge",
    "Tiana Fortune",
    "Tod 'The Blaster' McQuinn",
    "Trin Falcour",
    "Zacariah Nemo"
]
